name = "CthulhuVision"
uuid = "ecf23cb5-dfda-41a6-843c-cb4813e28e17"
authors = ["Erik Edin <erikedin@users.noreply.github.com>"]
version = "0.1.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
